### ISSUE TITLE
Everyone views custom highlighting or only me?

### ISSUE THREAD

**Issue by ghost** [ArchieMaclean/repl.it-color#1]
@macarc Everyone views custom highlighting or only me?

**Comment by macarc** [comment]
Hi, I'm not quite sure what you mean...could you elaborate please?

Thanks!

**Comment by ghost** [comment]
@macarc Your program changes default REPL.it highlighting? Highlighting changed by repl.it-color can see other people or only me?

**Comment by macarc** [comment]
Only you can see your custom theme, if that's what you mean.
